server:
  port: 8490
#  servlet:
#    session:
#      timeout: 1m
#  reactive:
#    session:
#      timeout: 1m



spring:
  profiles:
    active: dev # 디폴트 환경
  session:
    redis:
      repository-type: default



# BANNER
banner:
  location: classpath:banner.txt